#!/usr/bin/env bash
set -euo pipefail

echo "Preparing CPicoSDK build environment..."
echo "This build script is only needed to generate the CPicoSDK compound header file."
echo "After running it once, you can build your Swift packages that depend on CPicoSDK"
echo "without needing to run this script again unless you want to regenerate the header file."
echo
echo "You don't need to run this script if you are using CPicoSDK as a Swift Package dependency."

# Cleaning up existing build artifacts.
rm -rf .build
rm -rf Package.swift Package.resolved Sources/_CPicoSDK*
cp Package.swift.template Package.swift

export PREPARATION_SCRIPT_PATH="$(dirname "$0")/.env_prep"
SWIFTPM_BIN_DIR="${SWIFTPM_BIN_DIR:-}"
if [[ -z "$SWIFTPM_BIN_DIR" || ! -x "$SWIFTPM_BIN_DIR/swift-package" ]]; then
  echo "Set SWIFTPM_BIN_DIR to the Products directory containing the patched swift-package executable." >&2
  exit 1
fi
SWIFT_PACKAGE="$SWIFTPM_BIN_DIR/swift-package"

if command -v swiftly >/dev/null 2>&1; then
  export SWIFTLY_PATH="$(command -v swiftly)"
else
  echo "swiftly not found in PATH."
  echo "Install it from https://www.swift.org/download/"
  exit 1
fi

# Default path as generated by vscode-pico. You can also use pico-bootrstrap to generate this.
# Make sure to force the installation of the PicoSDK to this path with the versions reflected
# in env.json used below.
export PICO_SDK_BUNDLE_PATH="$HOME/.pico-sdk" 

# Set the swift build configuration. Based on checks it seems like this flag won't change the 
# resulting compound header file in a significant way. Keeping it here in case it does in the future.
export BUILD_TYPE="RelWithDebInfo" # Options: Debug, Release, RelWithDebInfo, MinSizeRel
export SWIFT_EXEC="${SWIFT_EXEC:-$($SWIFTLY_PATH run which swiftc)}"
export SWIFT_EXEC_MANIFEST="${SWIFT_EXEC_MANIFEST:-$SWIFT_EXEC}"

"$SWIFT_PACKAGE" --disable-sandbox prepare-rp2xxx-environment \
    --disable-vscode-settings \
    --disable-swift-sdk-staging \
    --dump-prep-script "$PREPARATION_SCRIPT_PATH" \
    --cpicosdk-envs-path "$(dirname "$0")/env.json" \
    --dont-force-product-name \
    --allow-writing-to-package-directory \
    --allow-network-connections all       # Used to download PicoSDK when not already present at PICO_SDK_BUNDLE_PATH.

source "$PREPARATION_SCRIPT_PATH"

"$SWIFT_PACKAGE" --disable-sandbox generate-cpicosdk --allow-writing-to-package-directory
echo "CPicoSDK build environment generated."
