function(cpicosdk_embed_resources TARGET_NAME RESOURCE_NAMES RESOURCE_PATHS)
    if(NOT RESOURCE_NAMES)
        return()
    endif()

    set(CPICOSDK_EMBEDDED_RESOURCE_NAMES ${RESOURCE_NAMES})
    set(CPICOSDK_EMBEDDED_RESOURCE_PATHS ${RESOURCE_PATHS})

    list(LENGTH CPICOSDK_EMBEDDED_RESOURCE_NAMES CPICOSDK_EMBEDDED_RESOURCE_NAMES_COUNT)
    list(LENGTH CPICOSDK_EMBEDDED_RESOURCE_PATHS CPICOSDK_EMBEDDED_RESOURCE_PATHS_COUNT)

    if(NOT CPICOSDK_EMBEDDED_RESOURCE_NAMES_COUNT EQUAL CPICOSDK_EMBEDDED_RESOURCE_PATHS_COUNT)
        message(FATAL_ERROR "CPicoSDK embedded resource names and paths must have the same length")
    endif()

    set(CPICOSDK_EMBEDDED_RESOURCE_OBJECTS)
    math(EXPR CPICOSDK_EMBEDDED_RESOURCE_LAST_INDEX "${CPICOSDK_EMBEDDED_RESOURCE_NAMES_COUNT} - 1")
    foreach(CPICOSDK_EMBEDDED_RESOURCE_INDEX RANGE 0 ${CPICOSDK_EMBEDDED_RESOURCE_LAST_INDEX})
        list(GET CPICOSDK_EMBEDDED_RESOURCE_NAMES ${CPICOSDK_EMBEDDED_RESOURCE_INDEX} CPICOSDK_EMBEDDED_RESOURCE_NAME)
        list(GET CPICOSDK_EMBEDDED_RESOURCE_PATHS ${CPICOSDK_EMBEDDED_RESOURCE_INDEX} CPICOSDK_EMBEDDED_RESOURCE_INPUT)

        set(CPICOSDK_EMBEDDED_RESOURCE_BIN "${CMAKE_CURRENT_BINARY_DIR}/cpicosdk_embedded_resources/${CPICOSDK_EMBEDDED_RESOURCE_NAME}")
        set(CPICOSDK_EMBEDDED_RESOURCE_OBJ "${CMAKE_CURRENT_BINARY_DIR}/cpicosdk_embedded_resources/${CPICOSDK_EMBEDDED_RESOURCE_NAME}.o")

        add_custom_command(
            OUTPUT "${CPICOSDK_EMBEDDED_RESOURCE_OBJ}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/cpicosdk_embedded_resources"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CPICOSDK_EMBEDDED_RESOURCE_INPUT}" "${CPICOSDK_EMBEDDED_RESOURCE_BIN}"
            COMMAND "${CMAKE_OBJCOPY}" -I binary -O elf32-littlearm -B arm
                "--rename-section" ".data=.rodata.cpicosdk_assets,alloc,load,readonly,data,contents"
                "${CPICOSDK_EMBEDDED_RESOURCE_NAME}" "${CPICOSDK_EMBEDDED_RESOURCE_OBJ}"
            DEPENDS "${CPICOSDK_EMBEDDED_RESOURCE_INPUT}"
            COMMENT "Embedding ${CPICOSDK_EMBEDDED_RESOURCE_INPUT} into ${CPICOSDK_EMBEDDED_RESOURCE_OBJ}"
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/cpicosdk_embedded_resources"
            VERBATIM
        )
        list(APPEND CPICOSDK_EMBEDDED_RESOURCE_OBJECTS "${CPICOSDK_EMBEDDED_RESOURCE_OBJ}")
    endforeach()

    target_sources("${TARGET_NAME}" PRIVATE ${CPICOSDK_EMBEDDED_RESOURCE_OBJECTS})
endfunction()
