import Foundation

@main
struct Main {
    enum Error: Swift.Error {
        case compilerCallFailed(Int32, String?)
        case compilerOutputFailedToDecode(any Swift.Error)

        var localizedDescription: String {
            switch self {
                case let .compilerCallFailed(status, error):
                    return "Compiler call failed with status \(status) and error: \(error ?? "no output")"
                case let .compilerOutputFailedToDecode(error):
                    return "Failed to decode compiler output: \(error)"
            }
        }
    }

    static func main() throws {
        let compiler = URL(fileURLWithPath: CommandLine.arguments[1])
        let input = URL(fileURLWithPath: CommandLine.arguments[2])
        let output = URL(fileURLWithPath: CommandLine.arguments[3])

        let process = Process()
        process.executableURL = compiler
        process.arguments = ["-o", "json", input.path]
        let (stdout, stderr) = (Pipe(), Pipe())
        process.standardOutput = stdout
        process.standardError = stderr

        try process.run()
        let (outputData, errorData) = (stdout.fileHandleForReading.readDataToEndOfFile(), stderr.fileHandleForReading.readDataToEndOfFile())
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            let errorString = String(data: errorData, encoding: .utf8)
            throw Error.compilerCallFailed(process.terminationStatus, errorString)
        }

        let compiledSource: CompiledSource
        do {
            compiledSource = try JSONDecoder().decode(CompiledSource.self, from: outputData)
        } catch {
            throw Error.compilerOutputFailedToDecode(error)
        }

        let result = Self.generateSwiftOutput(compiledSource: compiledSource)

        try result.write(to: output, atomically: true, encoding: .utf8)
    }

    static func generateSwiftOutput(compiledSource: CompiledSource) -> String {
        let globalVisibility = (compiledSource.programs.flatMap(\.langOpts)
            .last(where: { $0.lang.lowercased() == "swift" && $0.name.lowercased() == "globalVisibility" })?
            .value).map { "\($0) " } ?? ""

        var result = """
        import CPicoSDK

        // This file is autogenerated by pioasm-swift using pioasm version \(compiledSource.pioASMVersion) do not edit! //

        """ + "\n"
        
        for symbol in compiledSource.publicSymbols {
            result += """
            \(globalVisibility)let \(symbol.key) = \(symbol.value)
            """ + "\n"
        }

        for program in compiledSource.programs {
            let visibility = (program.langOpts
                .last(where: { $0.lang.lowercased() == "swift" && $0.name.lowercased() == "visibility" })?
                .value).map { "\($0) " } ?? ""

            result += """
            \(visibility)enum \(program.name) {
                \(visibility)static let wrap_target: UInt32 = \(program.wrapTarget)
                \(visibility)static let wrap: UInt32 = \(program.wrap)
                \(visibility)static let pio_version: UInt8 = \(program.pioVersion)
            """ + "\n"

            for symbol in program.publicSymbols {
                result += """
                    \(visibility)static let \(symbol.key) = \(symbol.value)
                """ + "\n"
            }

            for symbol in program.publicLabels {
                result += """
                    \(visibility)static let offset_\(symbol.key) = \(symbol.value)
                """ + "\n"
            }

            result += """

                \(visibility)static nonisolated(unsafe) let instructions: UnsafeBufferPointer<UInt16> = {
                    let instructions: [UInt16] = [
            """ + "\n"
            
            for (idx, instruction) in program.instructions.enumerated() {
                if idx == program.wrapTarget {
                    result += """
                                                // .wrap_target
                    """ + "\n"
                }

                for label in program.publicLabels.filter({ $0.value == idx }).keys {
                    result += """
                                                // \(label):
                    """ + "\n"                    
                }

                result += """
                                0x\(instruction.hex),     //     \(instruction.instruction.components(separatedBy: .newlines).joined(separator: ""))
                """ + "\n"

                if idx == program.wrap {
                    result += """
                                                // .wrap
                    """ + "\n"
                }
            }

            result += """
                    ]
                    let bufferPointer = UnsafeMutableBufferPointer<UInt16>.allocate(capacity: instructions.count)
                    let (_, index) = bufferPointer.initialize(from: instructions)
                    assert(index == instructions.endIndex, "Failed to initialize buffer pointer")
                    return UnsafeBufferPointer(bufferPointer)
                }()

                #if !PICO_NO_HARDWARE
                \(visibility)static nonisolated(unsafe) let program: UnsafePointer<pio_program_t> = {
                    let program = pio_program(
                        instructions: instructions.baseAddress!,
                        length: \(program.instructions.count),
                        origin: \(program.origin),
                        pio_version: Self.pio_version,
                        used_gpio_ranges: \(program.usedGPIORanges)
                    )
                    let pointer = UnsafeMutablePointer<pio_program_t>.allocate(capacity: 1)
                    pointer.initialize(to: program)
                    return UnsafePointer(pointer)
                }()

                \(visibility)static func get_default_config(offset: UInt32) -> pio_sm_config {
                    var c = pio_get_default_sm_config();
                    sm_config_set_wrap(&c, offset + Self.wrap_target, offset + Self.wrap)
            """ + "\n"

            if let `in` = program.in {
                result += """
                        sm_config_set_in_pin_count(&c, \(`in`.pinCount))
                        sm_config_set_in_shift(&c, \(`in`.right), \(`in`.autopush), \(`in`.threshold))
                """ + "\n"
            }
            
            if let out = program.out {
                result += """
                        sm_config_set_out_pin_count(&c, \(out.pinCount))
                        sm_config_set_out_shift(&c, \(out.right), \(out.autopush), \(out.threshold))
                """ + "\n"
            }

            if let setCount = program.setCount {
                result += """
                        sm_config_set_set_pin_count(&c, \(setCount))
                """ + "\n"
            }

            if let sideset = program.sideset {
                result += """
                        sm_config_set_sideset(&c, \(sideset.size), \(sideset.optional), \(sideset.pindirs))
                """ + "\n"
            }

            if let movStatus = program.movStatus {
                result += """
                        sm_config_set_mov_status(&c, \(movStatus.type), \(movStatus.n))
                """ + "\n"
            }

            if let fifoConfig = program.fifo {
                result += """
                        sm_config_set_fifo_join(&c, \(fifoConfig))
                """ + "\n"
            }

            if let clockDiv = program.clockDiv {
                result += """
                        sm_config_set_clkdiv_int_frac(&c, \(clockDiv.int), \(clockDiv.frac))
                """ + "\n"
            }

            result += """
                    return c;
                }
                #endif
            }

            """ + "\n"

            for codeBlock in program.codeBlocks.filter({ $0.lang.lowercased() == "swift" }) {
                result += codeBlock.contents + "\n"
            }
        }

        return result
    }
}
