name: Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-root:
    name: Root Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libhidapi-hidraw0 libhidapi-libusb0
      - name: Install swiftly
        run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
          tar zxf swiftly-$(uname -m).tar.gz && \
          ./swiftly init --quiet-shell-followup && \
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
          hash -r
      - name: Run root build script
        run: |
          chmod +x build.sh
          ./build.sh

  build-example:
    name: Example Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libhidapi-hidraw0 libhidapi-libusb0
      - name: Install swiftly
        run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
          tar zxf swiftly-$(uname -m).tar.gz && \
          ./swiftly init --quiet-shell-followup && \
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
          hash -r
      - name: Run example build script
        working-directory: Example
        run: |
          chmod +x build.sh
          ./build.sh
